#!/bin/bash 

# imports 
. $(dirname "$0")/import.sh 2>> /dev/null 
. $(dirname "$0")/tools/import.sh 2>> /dev/null 

import log 
import pkgi
import ask 
import conf

# HERE DOTFILES STARTS

echo "This is Daser2's Dotfiles script!"

askY "Are you ready to start?"
if [ $? -ne 1 ]
then
    log i "I... understand..."
    log i "Terminated."
    exit 0 
fi 

log i "Installing basic packages..."
pkgi git curl wget build make ninja cmake

pkginit

log i "Installing languages..."
pkgi gcc llvm lld clang bear lua luajit perl python jdk-openjdk kotlin node npm rust ghc nasm yasm fasm php dmd gfortran mono erlang elixir racket clisp

log i "Installing editors..."
pkgi vim neovim

log i "Copying vim configuration..."
conf vimrc .vimrc

log i "Copying bash configuration..."
conf bashrc .bashrc

log i "Instaling X11"
pkgi xorg xorg-xinit

choose "Choose env: " qtile i3
case "$?" in 
	0)
		log i "Installing QTile..."
		pkgi qtile

		log i "Copying X11 configuration..."
		conf xinitrc.qtile .xinitrc

		log i "Copying QTile configuration..."
		dotconf qtile qtile setup.py
		;;
	1)
		log i "Installing I3..."
		pkgi i3-wm i3status i3blocks
		
		log i "Copying X11 configuration..."
		conf xinitrc.i3 .xinitrc

		log i "Copying I3 configuration..."
		dotconf i3 i3 config
		;;
	*)
		log e "Unknown env."
		exit 1
		;;
esac

log i "Installing utils..."
pkgi ffmpeg feh alacritty thunar thunar-archive-plugin gvfs rofi

librewolf --version
if [ $? -ne 0 ]
then
	log i "Installing Librewolf..."
	pkgi librewolf
else
	log w "Librewolf already installed!"
fi

log i "Copying wallpapers..."
mkdir ~/Pictures ~/Pictures/wallpapers
cp $(dirname "$0")/assets/wallpaper.png ~/Pictures/wallpapers

